package server

import (
	"net/http"
	"path/filepath"
	"strings"

	"github.com/go-chi/chi/v5"
	"github.com/go-chi/chi/v5/middleware"
)

func (s *Server) routes() http.Handler {
	r := chi.NewRouter()
	r.Use(middleware.Recoverer)
	r.Use(s.requestLogger())
	if s.auth != nil {
		r.Use(s.auth.Middleware())
	}

	r.Get("/api/auth/state", s.auth.HandleState)
	r.Post("/api/auth/setup", s.auth.HandleSetup)
	r.Post("/api/auth/login", s.auth.HandleLogin)
	r.Post("/api/auth/logout", s.auth.HandleLogout)
	r.Post("/api/auth/recovery", s.auth.HandleRecovery)
	r.Post("/api/auth/enable-login", s.handleAuthEnableLogin)
	r.Post("/api/auth/change-password", s.auth.HandleChangePassword)
	r.Post("/api/auth/reauth", s.auth.HandleReauth)
	r.Get("/api/health", s.handleHealth)
	r.Get("/api/amboss/health", s.handleAmbossHealthGet)
	r.Post("/api/amboss/health", s.handleAmbossHealthPost)
	r.Get("/api/system", s.handleSystem)
	r.Get("/api/disk", s.handleDisk)
	r.Get("/api/postgres", s.handlePostgres)
	r.Get("/api/bitcoin", s.handleBitcoin)
	r.Get("/api/bitcoin/active", s.handleBitcoinActive)
	r.Get("/api/bitcoin/source", s.handleBitcoinSourceGet)
	r.Post("/api/bitcoin/source", s.handleBitcoinSourcePost)
	r.Get("/api/mempool/fees", s.handleMempoolFees)
	r.Get("/api/bitcoin-local/status", s.handleBitcoinLocalStatus)
	r.Get("/api/bitcoin-local/config", s.handleBitcoinLocalConfigGet)
	r.Post("/api/bitcoin-local/config", s.handleBitcoinLocalConfigPost)
	r.Get("/api/elements/status", s.handleElementsStatus)
	r.Get("/api/elements/mainchain", s.handleElementsMainchainGet)
	r.Post("/api/elements/mainchain", s.handleElementsMainchainPost)
	r.Get("/api/lnd/status", s.handleLNDStatus)
	r.Get("/api/lnd/config", s.handleLNDConfigGet)
	r.Get("/api/lnd/upgrade/status", s.handleLNDUpgradeStatus)
	r.Get("/api/app/upgrade/status", s.handleAppUpgradeStatus)
	r.Get("/api/wizard/status", s.handleWizardStatus)
	r.Post("/api/wizard/bitcoin-remote", s.handleWizardBitcoinRemote)
	r.Post("/api/wizard/lnd/create-wallet", s.handleCreateWallet)
	r.Post("/api/wizard/lnd/init-wallet", s.handleInitWallet)
	r.Post("/api/wizard/lnd/unlock", s.handleUnlockWallet)
	r.Post("/api/actions/restart", s.handleRestart)
	r.Post("/api/actions/system", s.handleSystemAction)
	r.Get("/api/logs", s.handleLogs)
	r.Post("/api/lnd/config", s.handleLNDConfigPost)
	r.Post("/api/lnd/config/raw", s.handleLNDConfigRaw)
	r.Post("/api/lnd/upgrade", s.handleLNDUpgradeStart)
	r.Post("/api/app/upgrade/start", s.handleAppUpgradeStart)
	r.Get("/api/apps", s.handleAppsList)
	r.Get("/api/apps/storage-targets", s.handleAppStorageTargets)
	r.Post("/api/apps/{id}/install", s.handleAppInstall)
	r.Post("/api/apps/{id}/uninstall", s.handleAppUninstall)
	r.Post("/api/apps/{id}/start", s.handleAppStart)
	r.Post("/api/apps/{id}/stop", s.handleAppStop)
	r.Post("/api/apps/{id}/reset-admin", s.handleAppResetAdmin)
	r.Get("/api/apps/{id}/admin-password", s.handleAppAdminPassword)
	r.Get("/api/apps/electrs/status", s.handleElectrsStatus)
	r.Get("/api/notifications", s.handleNotificationsList)
	r.Get("/api/notifications/stream", s.handleNotificationsStream)
	r.Get("/api/notifications/telegram", s.handleTelegramNotificationsGet)
	r.Post("/api/notifications/telegram", s.handleTelegramNotificationsPost)
	r.Get("/api/notifications/backup/telegram", s.handleTelegramBackupGet)
	r.Post("/api/notifications/backup/telegram", s.handleTelegramBackupPost)
	r.Post("/api/notifications/backup/telegram/test", s.handleTelegramBackupTest)
	r.Get("/api/reports/range", s.handleReportsRange)
	r.Get("/api/reports/custom", s.handleReportsCustom)
	r.Get("/api/reports/summary", s.handleReportsSummary)
	r.Get("/api/reports/summary/custom", s.handleReportsSummaryCustom)
	r.Get("/api/reports/live", s.handleReportsLive)
	r.Get("/api/reports/movement/live", s.handleReportsMovementLive)
	r.Get("/api/reports/config", s.handleReportsConfigGet)
	r.Post("/api/reports/config", s.handleReportsConfigPost)
	r.Get("/api/depix/config", s.handleDepixConfig)
	r.Post("/api/depix/orders", s.handleDepixCreateOrder)
	r.Get("/api/depix/orders", s.handleDepixOrdersList)
	r.Get("/api/depix/orders/{id}", s.handleDepixOrderGet)
	r.Get("/api/boleto/config", s.handleBoletoConfig)
	r.Post("/api/boleto/activate", s.handleBoletoActivate)
	r.Get("/api/boleto/activate/status/{paymentHash}", s.handleBoletoActivateStatus)
	r.Post("/api/boleto/quote", s.handleBoletoQuote)
	r.Get("/api/boleto/status/{paymentHash}", s.handleBoletoStatus)
	r.Get("/api/terminal/status", s.handleTerminalStatus)
	r.Get("/api/shortcuts", s.handleShortcutsGet)
	r.Post("/api/shortcuts", s.handleShortcutsPost)
	r.Delete("/api/shortcuts/{id}", s.handleShortcutsDelete)

	r.Route("/api/onchain", func(r chi.Router) {
		r.Get("/utxos", s.handleOnchainUtxos)
		r.Get("/transactions", s.handleOnchainTransactions)
		r.Post("/utxos/metadata", s.handleUtxoMetadataUpsert)
		r.Post("/utxos/lock", s.handleUtxoLock)
		r.Post("/utxos/unlock", s.handleUtxoUnlock)
		r.Post("/utxos/bump", s.handleUtxoBump)
		r.Get("/utxos/groups", s.handleUtxoGroupsList)
		r.Post("/utxos/groups", s.handleUtxoGroupsUpsert)
		r.Post("/utxos/groups/{id}/assign", s.handleUtxoGroupAssign)
		r.Delete("/utxos/groups/{id}", s.handleUtxoGroupDelete)
		r.Get("/provenance", s.handleProvenanceGraph)
		r.Get("/provenance/status", s.handleProvenanceStatus)
		r.Get("/provenance/health", s.handleProvenanceHealth)
		r.Post("/provenance/rebuild", s.handleProvenanceRebuild)
	})

	r.Route("/api/wallet", func(r chi.Router) {
		r.Get("/summary", s.handleWalletSummary)
		r.Get("/activity", s.handleWalletActivity)
		r.Get("/payments/{paymentHash}", s.handleWalletPaymentDetail)
		r.Post("/address", s.handleWalletAddress)
		r.Post("/invoice", s.handleWalletInvoice)
		r.Post("/decode", s.handleWalletDecode)
		r.Post("/pay/preview", s.handleWalletPayPreview)
		r.Post("/pay/validated-route", s.handleWalletPayValidatedRoute)
		r.Post("/pay/mpp", s.handleWalletPayMPP)
		r.Post("/pay", s.handleWalletPay)
		r.Post("/send/preview", s.handleWalletSendPreview)
		r.Post("/send", s.handleWalletSend)
	})

	r.Route("/api/lnops", func(r chi.Router) {
		r.Get("/channels", s.handleLNChannels)
		r.Get("/peers", s.handleLNPeers)
		r.Get("/channel/peer-recommendations", s.handleLNChannelPeerRecommendations)
		r.Get("/network-map", s.handleLNNetworkMapGet)
		r.Get("/network-map/config", s.handleLNNetworkMapConfigGet)
		r.Post("/network-map/config", s.handleLNNetworkMapConfigPost)
		r.Get("/graph-explorer/status", s.handleGraphExplorerStatusGet)
		r.Get("/graph-explorer/search", s.handleGraphExplorerSearchGet)
		r.Get("/graph-explorer/nodes/{pubkey}/general", s.handleGraphExplorerGeneralGet)
		r.Get("/graph-explorer/nodes/{pubkey}/channels", s.handleGraphExplorerChannelsGet)
		r.Get("/graph-explorer/nodes/{pubkey}/closed", s.handleGraphExplorerClosedGet)
		r.Get("/graph-explorer/nodes/{pubkey}/fees", s.handleGraphExplorerFeesGet)
		r.Post("/graph-explorer/recompute", s.handleGraphExplorerRecomputePost)
		r.Get("/closed-channels", s.handleLNClosedChannels)
		r.Get("/watchtower", s.handleLNWatchtowers)
		r.Post("/sign-message", s.handleLNSignMessage)
		r.Post("/peer", s.handleLNConnectPeer)
		r.Post("/peer/disconnect", s.handleLNDisconnectPeer)
		r.Post("/peers/boost", s.handleLNBoostPeers)
		r.Post("/watchtower/add", s.handleLNWatchtowerAdd)
		r.Post("/watchtower/remove", s.handleLNWatchtowerRemove)
		r.Get("/autofee/config", s.handleAutofeeConfigGet)
		r.Post("/autofee/config", s.handleAutofeeConfigPost)
		r.Get("/autofee/channels", s.handleAutofeeChannelsGet)
		r.Post("/autofee/channels", s.handleAutofeeChannelsPost)
		r.Post("/autofee/run", s.handleAutofeeRun)
		r.Post("/autofee/refresh", s.handleAutofeeRefresh)
		r.Get("/autofee/status", s.handleAutofeeStatus)
		r.Get("/autofee/results", s.handleAutofeeResults)
		r.Get("/autofee/outcomes", s.handleAutofeeOutcomesGet)
		r.Post("/autofee/outcomes/measure", s.handleAutofeeOutcomesMeasureNow)
		r.Get("/channel-ranking", s.handleChannelRankingGet)
		r.Post("/channel-ranking/recompute", s.handleChannelRankingRecomputePost)
		r.Get("/channel-ranking/open-candidates", s.handleChannelOpenCandidatesGet)
		r.Post("/channel-ranking/open-candidates/recompute", s.handleChannelOpenCandidatesRecomputePost)
		r.Get("/channel-ranking/{channel_point}", s.handleChannelRankingItemGet)
		r.Get("/close-manager/status", s.handleCloseManagerStatusGet)
		r.Get("/close-manager/sessions", s.handleCloseManagerSessionsGet)
		r.Get("/close-manager/sessions/{id}", s.handleCloseManagerSessionGet)
		r.Get("/close-manager/sessions/{id}/events", s.handleCloseManagerSessionEventsGet)
		r.Post("/close-manager/sessions/{id}/recover", s.handleCloseManagerSessionRecoverPost)
		r.Post("/close-manager/sessions/{id}/force-close", s.handleCloseManagerSessionForceClosePost)
		r.Post("/close-manager/sessions/{id}/bump-fee", s.handleCloseManagerSessionBumpFeePost)
		r.Get("/channel/auto-heal", s.handleLNChanHealGet)
		r.Post("/channel/auto-heal", s.handleLNChanHealPost)
		r.Get("/channel/htlc-manager", s.handleLNHTLCManagerGet)
		r.Post("/channel/htlc-manager", s.handleLNHTLCManagerPost)
		r.Get("/channel/htlc-manager/logs", s.handleLNHTLCManagerLogs)
		r.Get("/channel/htlc-manager/failed", s.handleLNHTLCManagerFailed)
		r.Get("/payments/clean-failed", s.handleLNFailedPaymentsCleanerGet)
		r.Post("/payments/clean-failed", s.handleLNFailedPaymentsCleanerPost)
		r.Get("/channel/tor-peers", s.handleLNTorPeerCheckerGet)
		r.Post("/channel/tor-peers", s.handleLNTorPeerCheckerPost)
		r.Get("/channel/tor-peers/logs", s.handleLNTorPeerCheckerLogs)
		r.Post("/channel/scb/restore", s.handleLNSCBRestore)
		r.Get("/channel/fees", s.handleLNChannelFees)
		r.Post("/channel/open-preview", s.handleLNOpenChannelPreview)
		r.Post("/channel/open", s.handleLNOpenChannel)
		r.Post("/channel/open-batch-preview", s.handleLNBatchOpenChannelPreview)
		r.Post("/channel/open-batch", s.handleLNBatchOpenChannel)
		r.Post("/channel/pending-open/bump-fee", s.handleLNPendingOpenBumpFee)
		r.Post("/channel/close", s.handleLNCloseChannel)
		r.Post("/channel/fees", s.handleLNUpdateFees)
		r.Post("/channel/status", s.handleLNUpdateChanStatus)
		r.Get("/balanced-open/status", s.handleBalancedOpenStatusGet)
		r.Get("/balanced-open/sessions", s.handleBalancedOpenSessionsGet)
		r.Post("/balanced-open/sessions", s.handleBalancedOpenSessionsPost)
		r.Get("/balanced-open/sessions/{id}", s.handleBalancedOpenSessionGet)
		r.Get("/balanced-open/sessions/{id}/events", s.handleBalancedOpenSessionEventsGet)
		r.Post("/balanced-open/sessions/{id}/propose", s.handleBalancedOpenSessionProposePost)
		r.Post("/balanced-open/sessions/{id}/accept", s.handleBalancedOpenSessionAcceptPost)
		r.Post("/balanced-open/sessions/{id}/execute", s.handleBalancedOpenSessionExecutePost)
		r.Post("/balanced-open/sessions/{id}/retry-broadcast", s.handleBalancedOpenSessionRetryBroadcastPost)
		r.Post("/balanced-open/sessions/{id}/recover", s.handleBalancedOpenSessionRecoverPost)
		r.Post("/balanced-open/sessions/{id}/cancel", s.handleBalancedOpenSessionCancelPost)
		r.Get("/node-retirement/status", s.handleNodeRetirementStatusGet)
		r.Get("/node-retirement/sessions", s.handleNodeRetirementSessionsGet)
		r.Post("/node-retirement/sessions", s.handleNodeRetirementSessionsPost)
		r.Get("/node-retirement/sessions/{id}", s.handleNodeRetirementSessionGet)
		r.Get("/node-retirement/sessions/{id}/events", s.handleNodeRetirementSessionEventsGet)
		r.Get("/node-retirement/sessions/{id}/channels", s.handleNodeRetirementSessionChannelsGet)
		r.Post("/node-retirement/sessions/{id}/confirm-coop", s.handleNodeRetirementSessionConfirmCoopPost)
		r.Post("/node-retirement/sessions/{id}/decision", s.handleNodeRetirementSessionDecisionPost)
		r.Get("/node-retirement/sessions/{id}/transfer", s.handleNodeRetirementSessionTransferGet)
		r.Get("/succession/status", s.handleSuccessionStatusGet)
		r.Get("/succession/config", s.handleSuccessionConfigGet)
		r.Post("/succession/config", s.handleSuccessionConfigPost)
		r.Post("/succession/alive", s.handleSuccessionAlivePost)
		r.Post("/succession/simulate", s.handleSuccessionSimulatePost)
	})

	r.Route("/api/rebalance", func(r chi.Router) {
		r.Get("/config", s.handleRebalanceConfigGet)
		r.Post("/config", s.handleRebalanceConfigPost)
		r.Get("/overview", s.handleRebalanceOverview)
		r.Get("/channels", s.handleRebalanceChannels)
		r.Get("/pair-stats", s.handleRebalancePairStats)
		r.Get("/queue", s.handleRebalanceQueue)
		r.Get("/history", s.handleRebalanceHistory)
		r.Get("/sovereign-history", s.handleRebalanceSovereignHistory)
		r.Post("/run", s.handleRebalanceRun)
		r.Post("/stop", s.handleRebalanceStop)
		r.Post("/mission-control/reset", s.handleRebalanceMissionControlReset)
		r.Post("/channel/target", s.handleRebalanceChannelTarget)
		r.Post("/channel/auto", s.handleRebalanceChannelAuto)
		r.Post("/channel/manual-restart", s.handleRebalanceChannelManualRestart)
		r.Post("/channel/exclude", s.handleRebalanceExclude)
		r.Get("/metrics/baseline", s.handleRebalanceMetricsBaseline)
		r.Get("/stream", s.handleRebalanceStream)
	})

	r.Route("/api/chat", func(r chi.Router) {
		r.Get("/inbox", s.handleChatInbox)
		r.Get("/messages", s.handleChatMessages)
		r.Post("/send", s.handleChatSend)
	})

	r.HandleFunc("/terminal", s.handleTerminalProxy)
	r.HandleFunc("/terminal/ws", s.handleTerminalProxy)
	r.HandleFunc("/terminal/*", s.handleTerminalProxy)

	// Pagcoin Swap: local config + Tor SOCKS reverse proxy to the gateway onion.
	r.Get("/api/apps/pagcoinswap/config", s.handlePagcoinSwapConfigGet)
	r.Post("/api/apps/pagcoinswap/config", s.handlePagcoinSwapConfigPost)
	r.HandleFunc("/api/apps/pagcoinswap/proxy/*", s.handlePagcoinSwapProxy)

	staticDir := s.cfg.UI.StaticDir
	r.Get("/*", s.handleSPA(staticDir))

	return r
}

func (s *Server) handleSPA(staticDir string) http.HandlerFunc {
	fileServer := http.FileServer(http.Dir(staticDir))
	indexPath := filepath.Join(staticDir, "index.html")

	return func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path != "/" {
			path := strings.TrimPrefix(r.URL.Path, "/")
			if _, err := http.Dir(staticDir).Open(path); err == nil {
				fileServer.ServeHTTP(w, r)
				return
			}
		}

		http.ServeFile(w, r, indexPath)
	}
}
